### PR TITLE
[bug-f-windows]open zoom before login to the system

### PR DESCRIPTION
**Pull request by fish1968**

### CODE REVIEW

**Comment by fish1968** [comment]
OK to go!

**Comment by fish1968** [comment]
OK to go!

**Comment by fish1968** [comment]
I am sorry, I thought I was on my fork... Not mean to interrupt this place

**Comment by simula67** [comment]
Hi @fish1968. No need to apologise, I am OK with interruptions. I can merge this into my repository if you re-open it. But, I would appreciate it if you rewrite the comment to mention why the timer is needed.

**Comment by fish1968** [comment]
@simula67 Thanks for your feedback! Now, I see my added comment again, and realize that it is meangless without providing a reason / purpose.

**Pull request closed without merging**
